server:
  port: 8082
  wait-time-in-ms-when-sync-empty: 3000

spring:
  data:
    mongodb:
      uri: mongodb://admin:0079@localhost:27017/online_sales?authSource=admin
      auto-index-creation: true

application-version: 1.0