server:
  port: 8083
  wait-time-in-ms-when-sync-empty: 3000

spring:
  spring:
    profiles:
      active: native
  data:
      mongodb:
        uri: mongodb://admin:0079@localhost:27017/online_sales
        database: sale
        auto-index-creation: true

application:
  productServer:
    url: http://localhost:8082
    endpointConsultProduct: ${application.productService.url}/product
  clientService:
    url: http://localhost:8081
    endpointConsultClient: ${application.clientService.url}/client/isRegistered/{id}
application-version: 2.0